In [2]:
import pandas as pd
alunos = {'Nome':['Ricardo', 'Pedro', 'Roberto', 'Carlos'],
          'Nota':[4, 7, 5.5, 9],
          'Aprovado':['Não', 'Sim', 'Não', 'Sim']}

In [3]:
dataframe = pd.DataFrame(alunos)

In [4]:
print(dataframe)

      Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim


In [5]:
objeto1 = pd.Series([2, 6, 8, 18, 5])
print(objeto1)

0     2
1     6
2     8
3    18
4     5
dtype: int64


In [11]:
import numpy as np
array1 = np.array([6, 12, 7, 0, 3])
array2 = np.array([(2, 6, 8, 18, 5), (6, 12, 7, 0, 3)])
print(array1)
print(array2)

[ 6 12  7  0  3]
[[ 2  6  8 18  5]
 [ 6 12  7  0  3]]


In [14]:
objeto2 = pd.Series(array1)
print(objeto2)

0     6
1    12
2     7
3     0
4     3
dtype: int32
