In [3]:
import numpy as np
a = np.array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [7]:
b = np.array([(2, 5, 7), (5, 3, 9), (4, 8, 5)])

In [8]:
print(b)

[[2 5 7]
 [5 3 9]
 [4 8 5]]


In [12]:
c = np.eye(10)
print(c)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [13]:
b.max()

9

In [14]:
b.min()

2

In [15]:
b.sum()

48

In [16]:
b.mean()

5.333333333333333

In [17]:
b.std()

2.160246899469287